// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACYtPkp0vCELtGCqdNorNjz9X8UuCJGM8',
    appId: '1:457724897600:android:02307e79d17d2776daf2a5',
    messagingSenderId: '457724897600',
    projectId: 'parkease-new',
    storageBucket: 'parkease-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1IILzKoaNhBkIDXIoWazIFBIaXIjIjEM',
    appId: '1:457724897600:ios:3744ee46cbde1dd6daf2a5',
    messagingSenderId: '457724897600',
    projectId: 'parkease-new',
    storageBucket: 'parkease-new.firebasestorage.app',
    iosBundleId: 'com.example.smartParkingAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1IILzKoaNhBkIDXIoWazIFBIaXIjIjEM',
    appId: '1:457724897600:ios:3744ee46cbde1dd6daf2a5',
    messagingSenderId: '457724897600',
    projectId: 'parkease-new',
    storageBucket: 'parkease-new.firebasestorage.app',
    iosBundleId: 'com.example.smartParkingAppNew',
  );
}
